"""Centralized Phase 2B roles, permissions, and prototype policy."""

ROLE_PERSONNEL = 'PERSONNEL'
ROLE_WELFARE_OFFICER = 'WELFARE_OFFICER'
ROLE_COMMANDER = 'COMMANDER'
ROLE_ADMIN = 'ADMIN'

PERMISSION_VIEW_OWN_PROFILE = 'VIEW_OWN_PROFILE'
PERMISSION_VIEW_EMPLOYEE = 'VIEW_EMPLOYEE'
PERMISSION_VIEW_EMPLOYEES = 'VIEW_EMPLOYEES'
PERMISSION_REGISTER_EMPLOYEE = 'REGISTER_EMPLOYEE'
PERMISSION_RUN_PREDICTION = 'RUN_PREDICTION'
PERMISSION_VIEW_ALERTS = 'VIEW_ALERTS'
PERMISSION_DELETE_EMPLOYEE = 'DELETE_EMPLOYEE'
PERMISSION_VIEW_MODEL_ANALYTICS = 'VIEW_MODEL_ANALYTICS'
PERMISSION_MANAGE_USERS = 'MANAGE_USERS'
PERMISSION_VIEW_OWN_OPERATIONAL_RECORDS = 'VIEW_OWN_OPERATIONAL_RECORDS'
PERMISSION_VIEW_OPERATIONAL_RECORDS = 'VIEW_OPERATIONAL_RECORDS'
PERMISSION_MANAGE_OPERATIONAL_RECORDS = 'MANAGE_OPERATIONAL_RECORDS'
PERMISSION_VIEW_OPERATIONAL_SUMMARY = 'VIEW_OPERATIONAL_SUMMARY'
PERMISSION_SUBMIT_WELLNESS = 'SUBMIT_WELLNESS'
PERMISSION_VIEW_OWN_WELLNESS = 'VIEW_OWN_WELLNESS'
PERMISSION_VIEW_WELLNESS_RECORDS = 'VIEW_WELLNESS_RECORDS'
PERMISSION_CREATE_OWN_SUPPORT_REQUEST = 'CREATE_OWN_SUPPORT_REQUEST'
PERMISSION_VIEW_OWN_SUPPORT_REQUESTS = 'VIEW_OWN_SUPPORT_REQUESTS'
PERMISSION_VIEW_SUPPORT_REQUESTS = 'VIEW_SUPPORT_REQUESTS'
PERMISSION_MANAGE_SUPPORT_REQUESTS = 'MANAGE_SUPPORT_REQUESTS'

ROLE_PERMISSIONS = {
    ROLE_PERSONNEL: {
        PERMISSION_VIEW_OWN_PROFILE,
        PERMISSION_REGISTER_EMPLOYEE,
        PERMISSION_RUN_PREDICTION,
        PERMISSION_VIEW_OWN_OPERATIONAL_RECORDS,
        PERMISSION_SUBMIT_WELLNESS,
        PERMISSION_VIEW_OWN_WELLNESS,
        PERMISSION_CREATE_OWN_SUPPORT_REQUEST,
        PERMISSION_VIEW_OWN_SUPPORT_REQUESTS,
    },
    ROLE_WELFARE_OFFICER: {
        PERMISSION_VIEW_EMPLOYEE,
        PERMISSION_VIEW_EMPLOYEES,
        PERMISSION_RUN_PREDICTION,
        PERMISSION_VIEW_ALERTS,
        PERMISSION_VIEW_MODEL_ANALYTICS,
        PERMISSION_VIEW_OPERATIONAL_RECORDS,
        PERMISSION_MANAGE_OPERATIONAL_RECORDS,
        PERMISSION_VIEW_OPERATIONAL_SUMMARY,
        PERMISSION_VIEW_WELLNESS_RECORDS,
        PERMISSION_VIEW_SUPPORT_REQUESTS,
        PERMISSION_MANAGE_SUPPORT_REQUESTS,
    },
    ROLE_COMMANDER: {
        PERMISSION_VIEW_EMPLOYEES,
        PERMISSION_VIEW_ALERTS,
        PERMISSION_VIEW_MODEL_ANALYTICS,
        PERMISSION_VIEW_OPERATIONAL_SUMMARY,
    },
    ROLE_ADMIN: {
        PERMISSION_VIEW_OWN_PROFILE,
        PERMISSION_VIEW_EMPLOYEE,
        PERMISSION_VIEW_EMPLOYEES,
        PERMISSION_REGISTER_EMPLOYEE,
        PERMISSION_RUN_PREDICTION,
        PERMISSION_VIEW_ALERTS,
        PERMISSION_DELETE_EMPLOYEE,
        PERMISSION_VIEW_MODEL_ANALYTICS,
        PERMISSION_MANAGE_USERS,
        PERMISSION_VIEW_OPERATIONAL_RECORDS,
        PERMISSION_MANAGE_OPERATIONAL_RECORDS,
        PERMISSION_VIEW_OPERATIONAL_SUMMARY,
        PERMISSION_VIEW_WELLNESS_RECORDS,
        PERMISSION_VIEW_SUPPORT_REQUESTS,
        PERMISSION_MANAGE_SUPPORT_REQUESTS,
    },
}
