import { useFocusEffect, useNavigation, useRoute } from '@react-navigation/native';
import type { RouteProp } from '@react-navigation/native';
import { useCallback, useRef, useState } from 'react';
import { ScrollView, StyleSheet, View } from 'react-native';

import { AlertStatusBadge } from '../../components/alerts/AlertStatusBadge';
import { AppButton } from '../../components/common/AppButton';
import { AppText } from '../../components/common/AppText';
import { ScreenContainer } from '../../components/common/ScreenContainer';
import { ErrorState } from '../../components/states/ErrorState';
import { LoadingState } from '../../components/states/LoadingState';
import { OfflineState } from '../../components/states/OfflineState';
import { useNetworkStatus } from '../../hooks/useNetworkStatus';
import { useAuth } from '../../auth/AuthContext';
import type { MainStackNavigation } from '../../navigation/MainNavigator';
import { getWelfareAlertDetail } from '../../services/alertService';
import type { MainStackParamList } from '../../types/navigation';
import type { WelfareAlert } from '../../types/alert';
import { theme } from '../../theme';
import { apiErrorMessage } from '../../utils/apiErrorMessage';

function formatTrigger(trigger: WelfareAlert['triggerType']): string {
  return trigger === 'REPEATED_ELEVATED_RISK'
    ? 'Repeated elevated risk'
    : 'Persistent high risk';
}

function formatDate(value: string): string {
  const date = new Date(value);
  return Number.isNaN(date.getTime())
    ? value
    : date.toLocaleString(undefined, {
        year: 'numeric',
        month: 'short',
        day: 'numeric',
        hour: 'numeric',
        minute: '2-digit',
      });
}

export function AlertDetailScreen() {
  const navigation = useNavigation<MainStackNavigation>();
  const route =
    useRoute<RouteProp<MainStackParamList, 'AlertDetail'>>();
  const { alertId } = route.params;
  const { isOnline } = useNetworkStatus();
  const { session } = useAuth();
  const [alert, setAlert] = useState<WelfareAlert | null>(null);
  const [isLoading, setIsLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const requestInProgress = useRef(false);
  const requestId = useRef(0);

  const loadDetail = useCallback(async () => {
    if (isOnline === false) {
      requestId.current += 1;
      requestInProgress.current = false;
      setAlert(null);
      setError(null);
      setIsLoading(false);
      return;
    }
    if (requestInProgress.current) {
      return;
    }
    requestInProgress.current = true;
    const currentRequestId = ++requestId.current;
    setIsLoading(true);
    setError(null);
    try {
      const nextAlert = await getWelfareAlertDetail(alertId);
      if (requestId.current === currentRequestId) {
        setAlert(nextAlert);
      }
    } catch (loadError: unknown) {
      if (requestId.current === currentRequestId) {
        setAlert(null);
        setError(apiErrorMessage(loadError, 'This welfare alert is temporarily unavailable.', {
          forbidden: 'This welfare alert is not available for the current account.',
          not_found: 'This welfare alert could not be found.',
          server: 'This welfare alert is temporarily unavailable.',
        }));
      }
    } finally {
      if (requestId.current === currentRequestId) {
        requestInProgress.current = false;
        setIsLoading(false);
      }
    }
  }, [alertId, isOnline]);

  useFocusEffect(
    useCallback(() => {
      void loadDetail();
      return () => {
        requestId.current += 1;
        requestInProgress.current = false;
      };
    }, [loadDetail]),
  );

  return (
    <ScreenContainer style={styles.screen}>
      <ScrollView
        contentContainerStyle={styles.content}
        showsVerticalScrollIndicator={false}
      >
        <AppButton
          accessibilityLabel="Go back from Alert Details"
          onPress={() => navigation.goBack()}
          title="Back"
        />

        <View style={styles.header}>
          <AppText variant="title" style={styles.brand}>
            SURAKSHAI
          </AppText>
          <AppText variant="heading" style={styles.heading}>
            Support alert
          </AppText>
          <AppText variant="body" style={styles.description}>
            This support alert was generated by the welfare system. It is not a
            medical diagnosis.
          </AppText>
        </View>

        <OfflineState isOnline={isOnline} />

        {isOnline !== false && isLoading ? (
          <LoadingState message="Loading alert details..." />
        ) : null}

        {!isLoading && error ? (
          <ErrorState message={error} onRetry={() => void loadDetail()} retryDisabled={isOnline === false} />
        ) : null}

        {isOnline !== false && !isLoading && !error && alert ? (
          <View style={styles.detail}>
            <AlertStatusBadge status={alert.status} />
            <AppText variant="body" style={styles.value}>
              Support context: {formatTrigger(alert.triggerType)}
            </AppText>
            <AppText variant="body" style={styles.value}>
              Severity: {alert.severity}
            </AppText>
            <AppText variant="body" style={styles.value}>
              Risk category reported by the backend: {alert.currentRiskCategory}
            </AppText>
            <AppText variant="bodySmall" style={styles.metadata}>
              Reference date: {alert.referenceDate}
            </AppText>
            <AppText variant="bodySmall" style={styles.metadata}>
              Created: {formatDate(alert.createdAt)}
            </AppText>
            {alert.acknowledgedAt ? (
              <AppText variant="bodySmall" style={styles.metadata}>
                Acknowledged: {formatDate(alert.acknowledgedAt)}
              </AppText>
            ) : null}
            {alert.reviewedAt ? (
              <AppText variant="bodySmall" style={styles.metadata}>
                Reviewed: {formatDate(alert.reviewedAt)}
              </AppText>
            ) : null}
            {alert.resolvedAt ? (
              <AppText variant="bodySmall" style={styles.metadata}>
                Closed: {formatDate(alert.resolvedAt)}
              </AppText>
            ) : null}
            <AppText variant="bodySmall" style={styles.staffInfo}>
              Alert status and support actions are managed by authorized
              welfare staff.
            </AppText>
            {session?.user.role === 'PERSONNEL' ? (
              <AppButton
                accessibilityLabel="Request support for this alert"
                onPress={() => navigation.navigate('Support', { relatedAlertId: alert.alertId })}
                title="Request Support"
              />
            ) : null}
          </View>
        ) : null}

        <AppButton
          accessibilityLabel="Refresh alert details"
          disabled={isLoading || isOnline === false}
          loading={isLoading}
          onPress={() => void loadDetail()}
          title="Refresh"
        />
      </ScrollView>
    </ScreenContainer>
  );
}

const styles = StyleSheet.create({
  screen: {
    paddingHorizontal: 0,
    paddingVertical: 0,
  },
  content: {
    gap: theme.spacing.lg,
    paddingBottom: theme.spacing.xl,
    paddingHorizontal: theme.spacing.lg,
    paddingTop: theme.spacing.lg,
  },
  header: {
    gap: theme.spacing.sm,
  },
  brand: {
    color: theme.colors.accent,
  },
  heading: {
    color: theme.colors.primary,
  },
  description: {
    color: theme.colors.secondary,
  },
  detail: {
    backgroundColor: theme.colors.surface,
    borderColor: theme.colors.border,
    borderRadius: 14,
    borderWidth: 1,
    gap: theme.spacing.md,
    padding: theme.spacing.md,
  },
  value: {
    color: theme.colors.text,
  },
  metadata: {
    color: theme.colors.secondary,
  },
  staffInfo: {
    color: theme.colors.secondary,
    marginTop: theme.spacing.xs,
  },
});
