"""Canonical Phase 4 risk model feature schema and metadata contract."""

MODEL_FEATURES = [
    "duty_hours_7d_avg",
    "duty_hours_30d_avg",
    "night_duty_7d_count",
    "night_duty_30d_count",
    "night_duty_frequency_7d",
    "night_duty_frequency_30d",
    "workload_7d_avg",
    "workload_30d_avg",
    "workload_trend",
    "current_consecutive_duty_days",
    "max_consecutive_duty_days_30d",
    "days_since_most_recent_leave",
    "leave_days_30d",
    "leave_episodes_30d",
    "current_deployment_days",
    "deployment_days_30d",
    "deployment_count_30d",
    "training_hours_30d",
    "training_session_count_30d",
    "transfer_count_30d",
    "duty_hours_trend",
    "night_duty_trend",
    "average_tasks_30d",
    "high_workload_days_30d",
    "workload_duty_hours_mean_30d",
    "deployment_intensity_current",
    "sleep_quality",
    "fatigue_level",
    "perceived_stress",
    "mood_wellbeing",
    "wellness_available",
]

TARGET_CLASSES = ["LOW", "ELEVATED", "HIGH"]
TARGET_COLUMN = "risk_category"
EXCLUDED_METADATA_COLUMNS = {"personnel_id", "reference_date", "recommended_split"}

FEATURE_DESCRIPTIONS = {
    "duty_hours_7d_avg": "Average duty hours over the last 7 days",
    "duty_hours_30d_avg": "Average duty hours over the last 30 days",
    "night_duty_7d_count": "Night-duty days over the last 7 days",
    "night_duty_30d_count": "Night-duty days over the last 30 days",
    "night_duty_frequency_7d": "Night-duty frequency over the last 7 days",
    "night_duty_frequency_30d": "Night-duty frequency over the last 30 days",
    "workload_7d_avg": "Average workload over the last 7 days",
    "workload_30d_avg": "Average workload over the last 30 days",
    "workload_trend": "Recent workload compared with the 30-day baseline",
    "current_consecutive_duty_days": "Current consecutive duty days",
    "max_consecutive_duty_days_30d": "Maximum consecutive duty days in the last 30 days",
    "days_since_most_recent_leave": "Days since the most recent completed leave",
    "leave_days_30d": "Leave days in the last 30 days",
    "leave_episodes_30d": "Leave episodes in the last 30 days",
    "current_deployment_days": "Current deployment duration in days",
    "deployment_days_30d": "Deployment days in the last 30 days",
    "deployment_count_30d": "Deployment episodes in the last 30 days",
    "training_hours_30d": "Training hours in the last 30 days",
    "training_session_count_30d": "Training sessions in the last 30 days",
    "transfer_count_30d": "Transfers in the last 30 days",
    "duty_hours_trend": "Recent duty hours compared with the 30-day baseline",
    "night_duty_trend": "Recent night-duty rate compared with the 30-day baseline",
    "average_tasks_30d": "Average task count over the last 30 days",
    "high_workload_days_30d": "High-workload days in the last 30 days",
    "workload_duty_hours_mean_30d": "Mean workload duty hours over the last 30 days",
    "deployment_intensity_current": "Current deployment intensity",
    "sleep_quality": "Self-reported sleep quality",
    "fatigue_level": "Self-reported fatigue level",
    "perceived_stress": "Self-reported perceived stress",
    "mood_wellbeing": "Self-reported mood and wellbeing",
    "wellness_available": "Availability of authorized voluntary wellness data",
}

assert "personnel_id" not in MODEL_FEATURES
assert "reference_date" not in MODEL_FEATURES
assert "recommended_split" not in MODEL_FEATURES
assert "risk_category" not in MODEL_FEATURES
assert len(MODEL_FEATURES) == 31

FEATURE_SOURCE_MAP = {
    "duty_hours_7d_avg": {"source": "Phase 3C duty_records", "transformation": "7-day average duty hours"},
    "duty_hours_30d_avg": {"source": "Phase 3C duty_records", "transformation": "30-day average duty hours"},
    "night_duty_7d_count": {"source": "Phase 3C duty_records/workload_records", "transformation": "Count of nighttime duty days within 7-day window"},
    "night_duty_30d_count": {"source": "Phase 3C duty_records/workload_records", "transformation": "Count of nighttime duty days within 30-day window"},
    "night_duty_frequency_7d": {"source": "Phase 3C duty_records", "transformation": "Night-duty days divided by duty days in 7-day window"},
    "night_duty_frequency_30d": {"source": "Phase 3C duty_records", "transformation": "Night-duty days divided by duty days in 30-day window"},
    "workload_7d_avg": {"source": "Phase 3C workload_records", "transformation": "Average daily workload score in 7-day window"},
    "workload_30d_avg": {"source": "Phase 3C workload_records", "transformation": "Average daily workload score in 30-day window"},
    "workload_trend": {"source": "Phase 3C workload_records", "transformation": "7-day average minus 30-day average workload"},
    "current_consecutive_duty_days": {"source": "Phase 3C duty_records/workload_records", "transformation": "Current continuous duty streak from reference date"},
    "max_consecutive_duty_days_30d": {"source": "Phase 3C duty_records/workload_records", "transformation": "Maximum consecutive duty-day run in 30-day window"},
    "days_since_most_recent_leave": {"source": "Phase 3C leave_records", "transformation": "Days since latest completed leave"},
    "leave_days_30d": {"source": "Phase 3C leave_records", "transformation": "Total leave days in 30-day window"},
    "leave_episodes_30d": {"source": "Phase 3C leave_records", "transformation": "Count of leave episodes in 30-day window"},
    "current_deployment_days": {"source": "Phase 3C deployment_records", "transformation": "Current ongoing deployment duration in days"},
    "deployment_days_30d": {"source": "Phase 3C deployment_records", "transformation": "Deployment days in 30-day window"},
    "deployment_count_30d": {"source": "Phase 3C deployment_records", "transformation": "Deployment episode count in 30-day window"},
    "training_hours_30d": {"source": "Phase 3C training_records", "transformation": "Total training hours in 30-day window"},
    "training_session_count_30d": {"source": "Phase 3C training_records", "transformation": "Training session count in 30-day window"},
    "transfer_count_30d": {"source": "Phase 3C transfer_records", "transformation": "Transfer count in 30-day window"},
    "duty_hours_trend": {"source": "Phase 3C duty_records", "transformation": "7-day average duty hours minus 30-day average"},
    "night_duty_trend": {"source": "Phase 3C duty_records", "transformation": "7-day night-duty rate minus 30-day night-duty rate"},
    "average_tasks_30d": {"source": "Phase 3C workload_records", "transformation": "Average daily task count across 30-day window"},
    "high_workload_days_30d": {"source": "Phase 3C workload_records", "transformation": "Count of high-workload days in 30-day window"},
    "workload_duty_hours_mean_30d": {"source": "Phase 3C workload_records", "transformation": "Mean workload duty hours over 30 days"},
    "deployment_intensity_current": {"source": "Phase 3C deployment_records", "transformation": "Current deployment intensity category"},
    "sleep_quality": {"source": "Phase 3D wellness_assessments", "transformation": "Latest voluntary sleep score or missing if unavailable"},
    "fatigue_level": {"source": "Phase 3D wellness_assessments", "transformation": "Latest voluntary fatigue score or missing if unavailable"},
    "perceived_stress": {"source": "Phase 3D wellness_assessments", "transformation": "Latest voluntary stress score or missing if unavailable"},
    "mood_wellbeing": {"source": "Phase 3D wellness_assessments", "transformation": "Latest voluntary mood/wellbeing score or missing if unavailable"},
    "wellness_available": {"source": "Phase 3D consent + availability", "transformation": "1 if authorized wellness data is present, else 0"},
}
